name: grizzly_io
description: Readers and writers for several file formats (CSV, TSV, JSON, YAML, etc)
version: 2.2.2
homepage: https://github.com/Grizzly-dart/grizzly_io
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  intl: ^0.16.0
  http: ^0.12.0

dev_dependencies:
  test:
